server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Nag@15199
    url: jdbc:mysql://localhost:3306/nag
    username: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
        
    show-sql: true  
    

