server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Nag15188
    url: jdbc:mysql://mynewsqldb.ct91asccasgf.eu-west-2.rds.amazonaws.com:3306/restaurant
    username: admin
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        
    show-sql: true 

